## NUMPY

In [1]:
import numpy as np

## 1-d array

In [2]:
one_dim_array = np.array ([1,2,3,4,5])

In [3]:
one_dim_array.shape

(5,)

In [ ]:
one_dim_array[0]

In [5]:
arr1=np.arange(10)

In [ ]:
arr1

In [7]:
arr2 = np.arange(20,30)

In [8]:
arr2

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [9]:
arr1 + arr2

array([20, 22, 24, 26, 28, 30, 32, 34, 36, 38])

## math operations

In [11]:
sample_arr = np.arange (1,6)

In [12]:
# multiplication
sample_arr *5

array([ 5, 10, 15, 20, 25])

In [13]:
#divition
sample_arr / 5

array([0.2, 0.4, 0.6, 0.8, 1. ])

### indexing

In [15]:
#get [2,3,4]
sample_arr [1:-1]

array([2, 3, 4])

In [17]:
#even
sample_arr % 2 ==0

array([False,  True, False,  True, False])

In [18]:
sample_arr[sample_arr % 2 ==0]

array([2, 4])

## 2-D array

In [23]:
a_two_dim_arr = np.array([[2,2] , [2,2]])

In [24]:
a_two_dim_arr.shape

(2, 2)

In [25]:
a_two_dim_arr

array([[2, 2],
       [2, 2]])

In [36]:
# with arange, create 4 * 4 array (0 to 16) #divide all the items into rows and columns
four_by_four = np.arange(0, 16)
four_by_four = four_by_four.reshape (4,4)
four_by_four

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

## indexing 2-D

In [31]:
# get the first row
four_by_four[0]

array([0, 1, 2, 3])

In [34]:
# get the first column
four_by_four[:,0]

array([ 0,  4,  8, 12])